[package]
name = "gamecube-tools"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.41", features = ["derive"] }
num_enum = "0.7.4"
object = "0.37.1"
thiserror = "2.0.12"
zerocopy = { version = "0.8.26", features = ["derive"] }

