[package]
name = "gamecube-tools"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
clap = { version = "4.5.21", features = ["derive"] }
thiserror = "2.0.3"
zerocopy = { version = "0.8.10", features = ["derive"] }
